# Site settings
title: ikurochkin.github.io
email: igor.itl@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ikurochkin.github.io" # the base hostname & protocol for your site
twitter_username: igoritl
github_username:  ikurochkin

# Build settings
markdown: kramdown
